== Apache Zookeeper

Apache Kafka is using Apache Zookeeper to store configuration data as well as for cluster coordination (e.g. leader
election). To start and run Kafka broker, Zookeeper needs to be installed and available.

=== Installation on Linux

==== Prerequisites

Zookeeper requires following components to be installed:

* JRE 8

==== Installation procedure

Zookeeper can be installed using following installation procedure:

. Add new `zookeeper` user and group:
+
[source]
----
sudo groupadd zookeeper
sudo useradd -g zookeeper zookeeper
sudo passwd zookeeper
----
. Create directory `/opt/zookeeper` and set its ownership to the `zookeeper` user:
+
[source]
----
sudo mkdir /opt/zookeeper
sudo chown -R zookeeper:zookeeper /opt/zookeeper
----
. Download the latest stable version from Apache Zookeeper http://zookeeper.apache.org/releases.html[download website]
. Change the ownership of the downloaded archive and move it to the newly created directory
(replace `x.x.x` for the downloaded version of Zookeeper - e.g. `3.4.11`):
+
[source]
----
sudo chown -R zookeeper:zookeeper zookeeper-x.x.x.tar.gz
sudo mv zookeeper-x.x.x.tar.gz /opt/zookeeper
----
. Unpack the archive and delete it (replace `x.x.x` for the downloaded version of Zookeeper - e.g. `3.4.11`)
+
[source]
----
su - zookeeper
cd /opt/zookeeper
tar xvfz zookeeper-x.x.x.tar.gz -C /opt/zookeeper --strip-components=1
rm zookeeper-x.x.x.tar.gz
----
. Create directory `/var/lib/zookeeper` for storing Zookeeper data and set its ownership to the `zookeeper` user:
+
[source]
----
sudo mkdir /var/lib/zookeeper
sudo chown -R zookeeper:zookeeper /var/lib/zookeeper
----

=== Standalone configuration

Zookeper can run in a standalone mode with only a single instance. However since Kafka broker is fully dependent on
Zookeeper it will stop working almost immediately when the single Zookeeper instance becomes unavailable. Therefore the
standalone configuration is not recommended for production use cases.

Zookeeper is using properties file for configuration. The most important configuration options are:

`tickTime`:: Zookeeper's basic time unit (in milliseconds) used for heartbeats and session timeouts.
`dataDir`:: The directory where Zookeeper data are stored. Should be set to `/var/lib/zookeeper/` directory created
during installation.
`clientPort`:: Port number where clients can connect. Defaults to `2181`.

NOTE: The sample configuration file can be found in `conf/zoo_sample.cfg` in the Zookeeper installation directory.

Zookeeper configuration file should be located in `/opt/zookeeper/cong/zoo.cfg`. A basic example of the configuration
file can be found below. The configuration file should be owned by the `zookeeper` user.

[source]
----
timeTick=2000
dataDir=/var/lib/zookeeper/
clientPort=2181
----

Once the configuration file is prepared, Zookeeper can be started using following command. In case the configuration
file is not located in `/opt/zookeeper/cong/zoo.cfg` the command has to be adapted accordingly.

[source]
----
su - zookeeper
/opt/zookeeper/bin/zkServer.sh start conf/zoo.cfg
----

To stop running Zookeeper instance following command can be used:
[source]
----
su - zookeeper
/opt/zookeeper/bin/zkServer.sh stop conf/zoo.cfg
----

To restart running Zookeeper instance following command can be used:
[source]
----
su - zookeeper
/opt/zookeeper/bin/zkServer.sh stop conf/zoo.cfg
----

=== Replicated configuration

For production use cases it is strongly recommended to run a cluster of replicated Zookeeper instances.

TIP: Zookeeper clusters are sometimes also refer to as _ensembles_.

Zookeeper clusters usually consist of odd number of nodes. Zookeeper requires majority of cluster nodes to be available
to work. For example a cluster with 3 nodes requires at least 2 of them to be up and running. In other words it can
tolerate 1 node being down. Cluster consisting of 5 nodes requires at least 3 nodes to be available. In other words it
can tolerate 2 nodes being down.

TIP: Zookeeper can run in clusters with even number of nodes. The additional node however doesn't increase the
resiliency of the cluster. A cluster with 4 nodes requires at least 3 nodes to be available and can tolerate only 1 node
being down. Therefore it has exactly the same resiliency as a cluster with only 3 nodes.

The different Zookeeper nodes should be ideally placed into different data centers or network segments. Increasing the
number of Zookeeper nodes increases the workload spent on cluster synchronization. For most Kafka use cases Zookeeper
cluster with 3, 5 or 7 nodes should be fully sufficient.

Replicated Zookeeper configuration supports all configuration options supported by the standalone configuration.
Additional options are added for the cluster configuration:

`initLimit`:: Amount of time to allow followers to connect and sync to the cluster leader. The time is specified as
number of ticks (see the `timeTick` potion for more details).
`syncLimit`:: Amount of time for which followers can be behind the leader. The time is specified as number of ticks
(see the `timeTick` potion for more details).

In addition to the options above, every configuration file should contain a lost of servers which should be members of
the Zookeeper cluster. The server records should be specified in the format `server.id=hostname:port1:port2`, where:

`id`:: is the ID of the Zookeeper cluster node.
`hostname`:: is the hostname or IP address where the node listens for connections.
`port1`:: is the number of the port used for intercluster communication.
`port2`:: is the bumber of the port used for leader election.

Following example shows how the configuration file for Zookeeper cluster might look like:

[source]
----
timeTick=2000
dataDir=/var/lib/zookeeper/
clientPort=2181
initLimit=5
syncLimit=2

server.1=172.17.0.1:2888:3888
server.2=172.17.0.2:2888:3888
server.3=172.17.0.3:2888:3888
----

Each node in the Zookeeper cluster has to be assigned an `ID`. Node `ID` is configured in a file named `myid` which has
to be stored in the `dataDir` folder (e.g. `/var/lib/zookeeper/`). The `myid` files should contain only a single line
with the `ID` written as text. The `ID` can be any integer from 1 to 255. The `ID` has to be unique within the Zookeeper
cluster. This file has to be created manually on each
cluster node. Using this file, given Zookeeper instance will use the configuration from the corresponding line in the
configuration file to configure its listeners and use all other lines to identify other cluster members.

Once the configuration files are prepared, the individual cluster nodes should be started in the same way as standalone
Zookeeper instance.

==== Procedure

Follow this procedure *on each node* to start replicated Zookeeper cluster:

. Create the `myid` file as described above.
. Create the configuration file with list of all cluster members as described above.
. Start the instance using:
+
[source]
----
su - zookeeper
/opt/zookeeper/bin/zkServer.sh start conf/zoo.cfg
----

=== Additional configuration options

Following options should be consider depending on the exact usecase scenario:

`maxClientCnxns`:: Maximal number of simultaneously connected clients.
`autopurge.snapRetainCount`:: Number of data snapshots which will be retained. Default value is `3`.
`autopurge.purgeInterval`:: Interval in hours for puring snapshots. Default value is `0` (auto-purging disabled).

All available configuration options can be found in Apache Zookeeper
http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance[documentation].

=== Security



==== TLS

The latest version of Zookeeper currently doesn't support TLS for encryption or authentication.

=== Verify Zookeeper health